"""Guard the PyPI staging area against drift.

The staging package copy is regenerated by pypi_staging/prepare_staging.py
and gitignored; when a copy is present it must be byte-identical to the
root package (the RobustModelMaker manual-sync drift hazard, made a test).
The staging pyproject must also agree with the root on the essentials.
"""
from __future__ import annotations

import hashlib
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
STAGING = ROOT / "pypi_staging"


def _md5(path: Path) -> str:
    return hashlib.md5(path.read_bytes()).hexdigest()


def test_staging_package_matches_root_when_present():
    dst = STAGING / "robustsignalmaker"
    if not dst.exists():
        pytest.skip("staging not populated; run pypi_staging/prepare_staging.py")
    src = ROOT / "robustsignalmaker"
    src_files = {p.relative_to(src) for p in src.rglob("*")
                 if p.is_file() and "__pycache__" not in p.parts}
    dst_files = {p.relative_to(dst) for p in dst.rglob("*")
                 if p.is_file() and "__pycache__" not in p.parts}
    assert src_files == dst_files, "staging file set differs from the root package"
    for rel in sorted(src_files):
        assert _md5(src / rel) == _md5(dst / rel), f"staging drift in {rel}"
    # the copied metadata files must match too (2026-09-01 sweep: CHANGELOG
    # drifted unguarded)
    for name in ("LICENSE", "CHANGELOG.md"):
        if (STAGING / name).exists():
            assert _md5(ROOT / name) == _md5(STAGING / name), f"{name} drifted"


def test_dist_holds_only_the_current_version():
    """`twine upload dist/*` must not publish a stale build (2026-09-01
    sweep found 0.1.0 artifacts beside the 0.2.0 ones)."""
    import re

    dist = STAGING / "dist"
    if not dist.exists():
        pytest.skip("nothing built yet")
    version = re.search(r'^__version__ = "([^"]+)"',
                        (ROOT / "robustsignalmaker" / "__init__.py").read_text(),
                        re.MULTILINE).group(1)
    strays = [p.name for p in dist.glob("*") if version not in p.name]
    assert not strays, f"stale artifacts in dist/: {strays}"


def test_staging_pyproject_agrees_with_root_on_essentials():
    root_txt = (ROOT / "pyproject.toml").read_text()
    stag_txt = (STAGING / "pyproject.toml").read_text()
    for needle in ('name = "robustsignalmaker"',
                   'version = { attr = "robustsignalmaker.__version__" }',
                   'requires-python = ">=3.9"',
                   '"numpy>=1.24"', '"scipy>=1.10"', '"scikit-learn>=1.3"',
                   "Development Status :: 4 - Beta"):
        assert needle in root_txt, f"root pyproject lost: {needle}"
        assert needle in stag_txt, f"staging pyproject lost: {needle}"
    # the bespoke README is the point of the staging area
    assert 'readme = "README.md"' in stag_txt
    assert (STAGING / "README.md").read_text().startswith("# RobustSignalMaker")
